version: '3'
services:
  back_end:
    build:
      context: ./back_end
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./back_end:/back_end
    tty: true
  postgres:
    image: postgres:latest
    container_name: products_hunt_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data